version: '3'
services:
  bookstore-db:
    container_name: bookstore-db
    image: postgres:13.4-alpine
    environment:
      - 'POSTGRES_DB=bookstore_db'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432:5432'